apiVersion: v1
kind: Namespace
metadata:
  name: power-monitor
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: power-monitor-api
  labels:
    app: power-monitor-api
  namespace: power-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: power-monitor-api
  template:
    metadata:
      labels:
        app: power-monitor-api
    spec:
      containers:
      - name: power-monitor-api
        image: ghcr.io/soxprox/power-monitor-api:master
        ports:
        - name: port3000
          containerPort: 3000
        - name: port3001
          containerPort: 3001
        envFrom:
        - secretRef:
            name: power-monitor-api-secret
---
apiVersion: v1
kind: Service
metadata:
  name: power-monitor-api
  namespace: power-monitor
spec:
  ports:
  - name: port3000
    port: 3000
    targetPort: 3000
  - name: port3001
    port: 3001
    targetPort: 3001
  selector:
    app: power-monitor-api
  type: LoadBalancer
